tap "homebrew/bundle"
tap "redis-stack/redis-stack"

# Core Utils
brew "bzip2"
brew "openblas"
brew "openssl@3"
brew "readline"
brew "wget"
brew "zlib"

#shell
brew "zsh"
brew "starship"

#perf
brew "btop"

#Command Line extras
brew "eza"
brew "xz"
brew "fzf"
brew "htop"
brew "direnv"

# Databases and storage
brew "postgresql@15"
brew "pgvector"

#redis with search
cask "redis-stack"

# Python
brew "pyenv"
brew "cmake"
brew "ruff"
brew "pipx"
brew "uv"

# Rust 
brew "rust"

#Node 
brew "nvm"

#Clis
brew "flyctl"
brew "gh"

brew "semgrep"

#Casks
cask "raycast"
cask "warp"

#Quicklooks
cask "qlstephen" #Quicklook plugin

# 1Password
cask "1password-cli"

